### Neural Networks from scratch


In [9]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [10]:
data=pd.read_csv("train.csv")

In [11]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 785 columns]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2290 entries, 0 to 2289
Columns: 785 entries, label to pixel783
dtypes: float64(215), int64(570)
memory usage: 13.7 MB


In [13]:
data=np.array(data)
m,n=data.shape
np.random.shuffle(data)
#This split of the train.csv is to avoid over-fitting test data
data_dev=data[0:1000].T
Y_dev=data_dev[0]
X_dev=data_dev[1:n]
X_dev = X_dev / 255.

data_train=data[1000:m].T
Y_train=data_train[0]
X_train=data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [14]:
Y_train.shape

(1290,)

In [15]:
X_train.shape

(784, 1290)

In [16]:
X_train.shape

(784, 1290)

In [20]:
def init_params():
  W1=np.random.rand(10,784) - 0.5
  b1=np.random.rand(10,1) - 0.5
  W2=np.random.rand(10,10) - 0.5
  b2=np.random.rand(10,1) - 0.5
  return W1,b1,W2,b2

def ReLu(Z):
  return np.maximum(Z,0)

def deriv_ReLu(Z):
  return Z > 0

def softmax(Z):
  A = np.exp(Z)/np.sum(np.exp(Z),axis=0,keepdims=True)
  return A

def forward_prop(W1,b1,W2,b2,X):
  Z1=W1.dot(X) + b1
  A1=ReLu(Z1)
  Z2=W2.dot(A1)+b2
  A2=softmax(Z2)
  return Z1,A1,Z2,A2

#setting the index of the label to 1
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, int(Y.max()) + 1))
    one_hot_Y[np.arange(Y.size), Y.astype(int)] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(A1,A2,Y,W1,Z1,W2,Z2,X):
  one_hot_Y=one_hot(Y)
  dZ2= A2 - one_hot_Y
  dW2= 1/m * dZ2.dot(A1.T)
  db2 = (1 / m) * np.sum(dZ2)
  dZ1= W2.T.dot(dZ2) *  deriv_ReLu(Z1)
  dW1= 1/m * dZ1.dot(X.T)
  db1 = (1 / m) * np.sum(dZ1)
  return dW1,db1,dW2,db2

def update_params(dW1,db1,dW2,db2,W1,W2,b1,b2,alpha):
  W1= W1 - alpha * dW1
  b1= b1 - alpha * db1
  W2= W2 - alpha * dW2
  b2= b2 - alpha * db2
  return W1, b1 , W2, b2


In [23]:
def get_predictions(A2):
  return np.argmax(A2,0)

def get_accuracy(predictions,Y):
  print(predictions,Y)
  return np.sum(predictions==Y)/Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(A1, A2, Y, W1, Z1, W2, Z2, X)
        W1, b1, W2, b2 = update_params(dW1, db1, dW2, db2, W1, W2, b1, b2, alpha)
        if i % 1 == 0:  # Print every 10 iterations
            predictions = get_predictions(A2)
            accuracy = get_accuracy(predictions, Y)
            print("Iteration= ", i)
            print("Accuracy= ", accuracy)
    return W1, b1, W2, b2



In [24]:
W1,b1,W2,b2=gradient_descent(X_train,Y_train,200,0.1)

[7 9 9 ... 8 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  0
Accuracy=  0.1372093023255814
[7 9 9 ... 8 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  1
Accuracy=  0.1387596899224806
[7 9 9 ... 8 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  2
Accuracy=  0.13565891472868216
[7 9 9 ... 8 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  3
Accuracy=  0.1372093023255814
[7 9 9 ... 8 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  4
Accuracy=  0.13643410852713178
[7 9 9 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  5
Accuracy=  0.14263565891472868
[7 9 9 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  6
Accuracy=  0.15271317829457365
[7 9 9 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  7
Accuracy=  0.16279069767441862
[7 9 8 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  8
Accuracy=  0.17054263565891473
[7 9 8 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  9
Accuracy=  0.17674418604651163
[7 9 8 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Iteration=  10
Accuracy=  0.18449612403100776
[7 9 8 ... 7 8 8] [3. 0. 8. ... 3. 4. 8.]
Ite

### Neural Networks using Keras

In [25]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

X_train = train_data.drop(columns=['label']).values
y_train = train_data['label'].values
X_test = test_data.values

# Normalize the pixel values to be between 0 and 1
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
y_train = to_categorical(y_train)

model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(X_train.shape[1],)))  # Hidden layer with 10 units
model.add(Dense(10, activation='softmax'))  # Output layer with 10 units for classification (digits 0-9)


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=200, batch_size=32, validation_split=0.1)

# Make predictions on test data
predictions_probabilities = model.predict(X_test)
predictions = np.argmax(predictions_probabilities, axis=1)
print(predictions)

Epoch 1/200
242/242 [==============================] - 2s 3ms/step - loss: 1.2902 - accuracy: 0.6086 - val_loss: nan - val_accuracy: 0.8233
Epoch 2/200
242/242 [==============================] - 1s 2ms/step - loss: 0.5593 - accuracy: 0.8515 - val_loss: nan - val_accuracy: 0.8756
Epoch 3/200
242/242 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.8826 - val_loss: nan - val_accuracy: 0.8802
Epoch 4/200
242/242 [==============================] - 1s 2ms/step - loss: 0.3630 - accuracy: 0.8979 - val_loss: nan - val_accuracy: 0.9023
Epoch 5/200
242/242 [==============================] - 1s 2ms/step - loss: 0.3299 - accuracy: 0.9056 - val_loss: nan - val_accuracy: 0.8988
Epoch 6/200
242/242 [==============================] - 1s 2ms/step - loss: 0.3034 - accuracy: 0.9147 - val_loss: nan - val_accuracy: 0.9070
Epoch 7/200
242/242 [==============================] - 1s 2ms/step - loss: 0.2851 - accuracy: 0.9175 - val_loss: nan - val_accuracy: 0.9151
Epoch 8/200
242/242 

Writing a neural network from scratch and using a deep learning framework like Keras offer different advantages and considerations:

1. **Customization vs. Simplicity**:
    - **Writing from Scratch**: Building a neural network from scratch offers maximum customization. You have full control over every aspect of the network architecture, training loop, and optimization algorithms. However, it requires a deep understanding of neural networks and significant programming effort.
    - **Using Keras**: Keras provides a high-level API for building neural networks. It offers simplicity and ease of use, allowing you to quickly prototype and experiment with different architectures. Keras abstracts away many low-level details, making it accessible to beginners and researchers who want to focus on model design and experimentation rather than implementation details.

2. **Performance**:
    - **Writing from Scratch**: Implementing neural networks efficiently from scratch can be challenging and time-consuming. It requires optimizing code for performance, especially for large datasets and complex models.
    The accuracy is 71.39%.
    - **Using Keras**: Keras leverages highly optimized backend libraries like TensorFlow or PyTorch for computations. These libraries are optimized for performance on CPUs and GPUs, resulting in efficient execution of neural network operations. Keras models can be easily scaled and deployed in production environments. The accuracy is 90%.

3. **Community Support**:
    - **Writing from Scratch**: While implementing neural networks from scratch can be a great learning experience, you may have limited resources and community support compared to using established frameworks.
    - **Using Keras**: Keras has a large and active community of users and contributors. It provides extensive documentation, tutorials, and pre-trained models. You can leverage community-built tools and libraries to accelerate development and solve common problems.

4. **Debugging and Testing**:
    - **Writing from Scratch**: Debugging custom implementations can be challenging, especially when dealing with complex network architectures and optimization algorithms.
    - **Using Keras**: Keras provides built-in support for debugging and testing neural networks. You can easily visualize model architectures, monitor training progress, and debug issues using tools like TensorBoard.
